{{- range $serveName, $model := .Values.catalog }}
  {{- if $model.enabled }}
    {{- $modelName := "" }}
    {{- if eq $model.engine "OLlama" }}
      {{- $_ := set $ "modelName" (trimPrefix "ollama://" $model.url) }}
    {{- else if eq $model.engine "VLLM" }}
      {{- $_ := set $ "modelName" (trimPrefix "hf://" $model.url) }}
    {{- else }}
      {{- $_ := set $ "modelName" "" }}
    {{- end }}
    {{- $modelName := $.modelName }}
---
apiVersion: v1
kind: Service
metadata:
  name: model-{{ regexReplaceAll "[^a-zA-Z0-9-]" (lower $serveName) "-" }}
  labels:
    app: "model-{{ $serveName }}"
    model: "{{ regexReplaceAll "[^a-zA-Z0-9-.]" $modelName "-" }}"

  {{- with $.Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}

spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "model-{{ $serveName }}"
    model: "{{ regexReplaceAll "[^a-zA-Z0-9-.]" $modelName "-" }}"

  {{- end }}
{{- end }}