{{ if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: "ui-deploy"

spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "ui-deploy"

{{ end }}