
catalog:

  # Mistral cpu#
  e5-mistral-7b-instruct-vllm-cpu:
    enabled: false
    features: ["TextEmbedding"]
    url: "hf://intfloat/e5-mistral-7b-instruct"
    engine: VLLM
    # TODO: Adjust - the memory associated with this request is too low.
    resourceProfile: cpu
    args:
    - --gpu-memory-utilization=0.9


  # Llama cpu #
  llama-3.1-8b-instruct-vllm-cpu:
    enabled: false
    features: ["TextGeneration"]
    url: "hf://meta-llama/Meta-Llama-3.1-8B-Instruct"
    engine: VLLM
    resourceProfile: cpu
    env:
      VLLM_CPU_KVCACHE_SPACE: "4"
    args:
    - --max-model-len=32768
    - --max-num-batched-token=32768
    
    
