imagePullSecrets:
  #- name: my-registry-secret


###############################################################################
modelCache:
  persistence:
    enabled: true
    storageClassName: "local-path"
    size: "10Gi"
    accessModes:
      - "ReadWriteOnce"
      #- "ReadWriteMany"
    annotations:
      "helm.sh/resource-policy": "keep"
      "kubernetes.io/pvc-protection": "true"
  service:
    port: 80
    annotations:
      


###############################################################################
modelServers:
  VLLM:
    images:
      # The key is the image name (referenced from resourceProfiles) and the value is the image.
      # The "default" image should always be specified.
      # "default" is used when no imageName is specified or if a specific image is not found.
      default: "vllm/vllm-openai:v0.8.3"
      #nvidia-gpu: "vllm/vllm-openai:v0.8.3"
      #cpu: "substratusai/vllm:v0.6.3.post1-cpu"
  OLlama:
    images:
      default: "ollama/ollama:latest"



###############################################################################
resourceProfiles:
  cpu:
    imageName: "cpu"
    requests:
      cpu: 2
      # TODO: Consider making this a ratio that is more common on cloud machines
      # such as 1:4 CPU:Mem. NOTE: This might need to be adjusted for local clusters.
      memory: "8Gi"
      # TODO: Consider adding eph storage requests/limits.
      # Perhaps this is just needed for GKE Autopilot which defaults
      # to 1Gi for CPU-only.
      # ephemeral-storage: "2Gi"
    limits:
      cpu: 12
      memory: "24Gi"
  
  nvidia-gpu:
    imageName: "nvidia-gpu"
    runtimeClassName: "nvidia"
    requests:
      nvidia.com/gpu: "1"
      cpu: 2
      memory: "4Gi"
    limits:
      nvidia.com/gpu: "1"
      cpu: 12
      memory: "8Gi"
    # tolerations:
    #   - key: "nvidia.com/gpu"
    #     operator: "Equal"
    #     value: "present"
    #     effect: "NoSchedule"
    # nodeSelector:
    #   nvidia.com/gpu.family: "ampere"
    #   nvidia.com/gpu.memory: "81614088"



###############################################################################
catalog:


